= qlearner
:travispage: https://travis-ci.org/Cantido/qlearner
:travisimage: https://travis-ci.org/Cantido/qlearner.svg?branch=master

image::{travisimage}[alt="Build Status", link={travispage}]


A demonstration of the q-learning reinforcement learning technique. For more
information about the technique itself, see the
link:https://en.wikipedia.org/wiki/Q_learning[Wikipedia page on Q-Learning].

This program uses the q-learning technique to move an agent through a grid.
There is a starting square and a goal square, and the agent has to
learn, using q-learning, how to reach the goal in the fewest number of moves.

== Usage

See the `qlearner-core` module for the core library. Its tests build a
"`Grid World`" implementation that functions as a simple example.

License
-------

(C) Robert Richter 2016

Released under the link:http://www.gnu.org/licenses/gpl.html[GNU General Public License, Version 3]

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.